<a href="https://colab.research.google.com/github/CarlosFranciscoM-Urzua/EJERCICIOS_PLN_COLAB/blob/main/BIGRAMAS_UNIGRAMAS_Y_SPARCITY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Carlos Francisco Montoya Urzúa

9 de Octubre de 2026

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

#CORPUS
corpus = [
    'el coche es rapido',
    'el coche es azul',
    'un coche rapido azul'
]

vectorizador = CountVectorizer()
matriz_dispersa = vectorizador.fit_transform(corpus)

df_unigramas = pd.DataFrame(
    matriz_dispersa.toarray(),
    columns=vectorizador.get_feature_names_out()
)
df_unigramas.index = ['Documento 1', 'Documento 2', 'Documento 3']

print("Matriz de Unigramas")
display(df_unigramas)

#BIGRAMAS
vectorizador_bigramas = CountVectorizer(ngram_range=(2,2))
matriz_bigramas = vectorizador_bigramas.fit_transform(corpus)

df_bigramas = pd.DataFrame(
    matriz_bigramas.toarray(),
    columns = vectorizador_bigramas.get_feature_names_out()
)
df_bigramas.index = ['Documento 1', 'Documento 2', 'Documento 3']

print('MATRIZ DE BIGRAMAS')
display(df_bigramas)

#FUNCION PARA CALCULAR SPARCITY
def calcular_sparcity(matriz):
    total_celdas = matriz.size
    cantidad_ceros = np.count_nonzero(matriz == 0)
    return cantidad_ceros / total_celdas

sparsity_unigramas = calcular_sparcity(df_unigramas.to_numpy())
sparsity_bigramas = calcular_sparcity(df_bigramas.to_numpy())

#RESUMEN
resumen = pd.DataFrame({
    'Representacion': ['Unigramas', 'Bigramas'],
    'Documentos': [df_unigramas.shape[0], df_bigramas.shape[0]],
    'Caracteristicas': [df_unigramas.shape[1], df_bigramas.shape[1]],
    'Sparcity': [sparsity_unigramas, sparsity_bigramas]
})

resumen['Sparcity'] = resumen['Sparcity'].map(lambda x: f"{x:.2%}")

print('COMPARACION')
display(resumen)

Matriz de Unigramas

             azul  coche  el  es  rapido  un
Documento 1     0      1   1   1       1   0
Documento 2     1      1   1   1       0   0
Documento 3     1      1   0   0       1   1

MATRIZ DE BIGRAMAS

,coche es,coche rapido,el coche,es azul,es rapido,rapido azul,un coche
Documento 1,1,0,1,0,1,0,0
Documento 2,1,0,1,1,0,0,0
Documento 3,0,1,0,0,0,1,1

COMPARACION

  Representacion  Documentos  Caracteristicas Sparcity
0      Unigramas           3                6   33.33%
1       Bigramas           3                7   57.14%

#Actividad de análisis para el estudiante
1. **¿Cuántos términos únicos se obtuvieron con unigramas?**

6 términos

2. **¿Cuántos bigramas únicos se obtuvieron?**

7 bigramas

3. **¿Por qué el numero de filas no cambia entre ambas matrices?**

Porque es el número de documentos en el corpues

4. **¿Qué significa el valor 0 en una celda de la matriz?**

Que no aparece un determinado elemento.

5. **¿Qué significa el valor 1?¿Podría aparecer un valor 2 o mayor?**

Que hubo apariciones de un elemento. No puede haber valores mayores ya que la matriz es binaria.

6. **¿Cuál representación presenta mayor sparcity en el corpus utilizado?**

La representación con bigramas

7. **¿Por qué los bigramas son más sensibles al orden de las palabras?**

Porque los bigramas sí mantienen un sentido de orden.

8. **¿Qué problema podria producir una matriz con miles de columnas y la gran mayoria de ceros?**

Que necesite un gran espacio en memoria para almacenarse, y la gran mayoria de esa informacion es innecesaria.

9. **¿Por qué scikit-learn conserva originalmente la matriz como dispersa en lugar de convertirla automáticamente con toarray()?**

Porque la matriz dispersa requiere menos espacio en memoria.

10. **¿En qué situación podría ser útil usar bigramas a pesar del aumento de la dimensionalidad?**

En situacioens donde es importante conservar el orden de las palabras. Por ejemplo:
* **Análisis de sentimiento (manejo de negaciones):** Para distinguir entre "bueno" y "no bueno" (el unigrama pierde la relación, el bigrama la conserva).
* **Desambiguación de términos compuestos:** Para identificar conceptos que cambian de significado al separarse, como "red social", "bajo costo" o "buenos aires".

In [ ]:
vectorizador_mixto =CountVectorizer(ngram_range=(1,2))
matriz_mixta = vectorizador_mixto.fit_transform(corpus)

df_mixta = pd.DataFrame(
    matriz_mixta.toarray(),
    columns= vectorizador_mixto.get_feature_names_out()
)

print("DImension: ", df_mixta.shape)
display(df_mixta)

sparcity_mixta = calcular_sparcity(df_mixta.to_numpy())
print(f"Sparcity unigrmas + bigramas: {sparcity_mixta:.2%}")

DImension:  (3, 13)

,azul,coche,coche es,coche rapido,el,el coche,es,es azul,es rapido,rapido,rapido azul,un,un coche
0,0,1,1,0,1,1,1,0,1,1,0,0,0
1,1,1,1,0,1,1,1,1,0,0,0,0,0
2,1,1,0,1,0,0,0,0,0,1,1,1,1

Sparcity unigrmas + bigramas: 46.15%